### ISSUE TITLE
EBICS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by gerwald** [hohlerde/NetEbics#2]
When Announce my Signature to the Banking Server, I get the following Error
```
{
"TechnicalReturnCode": 61099,
"BusinessReturnCode": 0,
"ReportText": "[EBICS_INTERNAL_ERROR] interner EBICS-Fehler"
}
```

I would desperately need some help here - could you maybe be so kind and contact me via Email? (see my profile page)
THANKS!

**Comment by hohlerde** [comment]
Sorry for the late reply. Was a bit busy the last days. I don't have an ebics banking account anymore, so not sure if I can really help. How did you submit your banking keys (ini/hia) and which auth/crypt versions did you set in the request?

**Comment by Genesis171** [comment]
Hi hohlerde.
The authentication signature is not valid for french banK. Can you help me?

**Comment by hohlerde** [comment]
Hi Genesis171. Unfortunately I have no access anymore to a EBICS account, so there is little I can do. I have only tested the implementation with a German bank account. However,  there is a java implementation which works with french banks, if I remember correctly.

https://github.com/uwemaurer/ebics-java-client

**Comment by hohlerde** [comment]
Closing because of archiving/moving.
